DROP TABLE IF EXISTS AUCTION;
DROP TABLE IF EXISTS ITEM;

CREATE TABLE ITEM (
 ITEM_ID VARCHAR(250) PRIMARY KEY,
 ITEM_DESCRIPTION VARCHAR(250) DEFAULT NULL
);

CREATE TABLE AUCTION (
  AUCTION_ITEM_ID INT AUTO_INCREMENT  PRIMARY KEY,
  CURRENT_BID DECIMAL,
  MAX_AUTO_BID_AMT DECIMAL,
  RESERVE_PRICE DECIMAL NOT NULL,
  BIDDER_NAME VARCHAR(250) DEFAULT NULL,
  ITEM_ID VARCHAR(250),
  FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ITEM_ID)
);
